name: data_layer
description: Access to persistence data layer
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.7.0

dependencies:

  freezed_annotation: ^3.0.0
  get_it: ^8.0.3
  json_annotation: ^4.9.0

  postgres: ^3.5.6
  dio: ^5.8.0+1

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.25.8
  freezed: ^3.0.5
  very_good_analysis: ^6.0.0
  build_runner: ^2.4.15
  json_serializable: ^6.8.0

flutter:
  generate: true
