import 'package:data_layer/src/entities/product/product_entity.dart';

List<Product> products = [
  Product(
    id: 10,
    name: 'Bánh Mì',
    description: 'Vietnamese sandwich',
    price: 30000.0,
    category: 'Food',
  ),
  Product(
    id: 11,
    name: 'Phở Gà',
    description: 'Vietnamese chicken noodle soup',
    price: 45000.0,
    category: 'Food',
  ),
  Product(
    id: 12,
    name: 'Cà Phê Sữa Đá',
    description: 'Vietnamese iced coffee with condensed milk',
    price: 25000.0,
    category: 'Beverages',
  ),
  Product(
    id: 13,
    name: 'Gỏi Cuốn',
    description: 'Fresh spring rolls',
    price: 35000.0,
    category: 'Food',
  ),
  Product(
    id: 14,
    name: 'Nước Dừa',
    description: 'Fresh coconut water',
    price: 20000.0,
    category: 'Beverages',
  ),
  Product(
    id: 15,
    name: 'Bún Chả',
    description: 'Grilled pork with vermicelli noodles',
    price: 50000.0,
    category: 'Food',
  ),
  Product(
    id: 16,
    name: 'Chè',
    description: 'Sweet dessert soup',
    price: 25000.0,
    category: 'Dessert',
  ),
  Product(
    id: 17,
    name: 'Nem Rán',
    description: 'Fried spring rolls',
    price: 40000.0,
    category: 'Food',
  ),
  Product(
    id: 18,
    name: 'Sinh Tố',
    description: 'Fruit smoothie',
    price: 30000.0,
    category: 'Beverages',
  ),
  Product(
    id: 19,
    name: 'Bánh Xèo',
    description: 'Sizzling Vietnamese pancake',
    price: 40000.0,
    category: 'Food',
  ),
  Product(
    id: 20,
    name: 'Sữa Chua Nếp Cẩm',
    description: 'Black sticky rice yogurt',
    price: 25000.0,
    category: 'Dessert',
  ),
  Product(
    id: 21,
    name: 'Bún Bò Huế',
    description: 'Spicy beef noodle soup from Hue',
    price: 55000.0,
    category: 'Food',
  ),
  Product(
    id: 22,
    name: 'Trà Đá',
    description: 'Iced tea',
    price: 10000.0,
    category: 'Beverages',
  ),
  Product(
    id: 23,
    name: 'Mì Quảng',
    description: 'Turmeric noodles from Quảng Nam',
    price: 45000.0,
    category: 'Food',
  ),
  Product(
    id: 24,
    name: 'Kem Dừa',
    description: 'Coconut ice cream',
    price: 30000.0,
    category: 'Dessert',
  ),
  Product(
    id: 25,
    name: 'Bánh Cuốn',
    description: 'Steamed rice rolls',
    price: 35000.0,
    category: 'Food',
  ),
  Product(
    id: 26,
    name: 'Nước Mía',
    description: 'Sugarcane juice',
    price: 15000.0,
    category: 'Beverages',
  ),
  Product(
    id: 27,
    name: 'Hủ Tiếu',
    description: 'Southern Vietnamese noodle soup',
    price: 40000.0,
    category: 'Food',
  ),
  Product(
    id: 28,
    name: 'Bánh Flan',
    description: 'Vietnamese flan cake',
    price: 20000.0,
    category: 'Dessert',
  ),
  Product(
    id: 29,
    name: 'Phở Cuốn',
    description: 'Fresh pho rolls',
    price: 35000.0,
    category: 'Food',
  ),
  Product(
    id: 30,
    name: 'Rau Má Đậu Xanh',
    description: 'Pennywort drink with mung bean',
    price: 25000.0,
    category: 'Beverages',
  ),
  Product(
    id: 31,
    name: 'Bánh Cam',
    description: 'Sesame balls',
    price: 15000.0,
    category: 'Dessert',
  ),
  Product(
    id: 32,
    name: 'Cơm Tấm',
    description: 'Broken rice with grilled pork',
    price: 45000.0,
    category: 'Food',
  ),
  Product(
    id: 33,
    name: 'Soda Chanh',
    description: 'Lime soda',
    price: 20000.0,
    category: 'Beverages',
  ),
  Product(
    id: 34,
    name: 'Bánh Bò',
    description: 'Steamed rice cake',
    price: 15000.0,
    category: 'Dessert',
  ),
  Product(
    id: 35,
    name: 'Canh Chua',
    description: 'Sweet and sour fish soup',
    price: 50000.0,
    category: 'Food',
  ),
  Product(
    id: 36,
    name: 'Bia Hơi',
    description: 'Draft beer',
    price: 18000.0,
    category: 'Beverages',
  ),
  Product(
    id: 37,
    name: 'Xôi Xéo',
    description: 'Sticky rice with mung bean and fried onion',
    price: 25000.0,
    category: 'Food',
  ),
  Product(
    id: 38,
    name: 'Chè Chuối',
    description: 'Banana and coconut milk dessert',
    price: 20000.0,
    category: 'Dessert',
  ),
  Product(
    id: 39,
    name: 'Bò Lá Lốt',
    description: 'Grilled beef in wild betel leaves',
    price: 55000.0,
    category: 'Food',
  ),
  Product(
    id: 40,
    name: 'Trà Sữa Trân Châu',
    description: 'Bubble milk tea',
    price: 35000.0,
    category: 'Beverages',
  ),
  Product(
    id: 41,
    name: 'Bánh Khọt',
    description: 'Mini savory pancakes',
    price: 40000.0,
    category: 'Food',
  ),
  Product(
    id: 42,
    name: 'Tàu Hũ Nóng',
    description: 'Hot tofu pudding',
    price: 15000.0,
    category: 'Dessert',
  ),
  Product(
    id: 43,
    name: 'Lẩu',
    description: 'Vietnamese hot pot',
    price: 200000.0,
    category: 'Food',
  ),
  Product(
    id: 44,
    name: 'Nước Ép Trái Cây',
    description: 'Fresh fruit juice',
    price: 30000.0,
    category: 'Beverages',
  ),
  Product(
    id: 45,
    name: 'Bánh Mì Chảo',
    description: 'Vietnamese skillet bread',
    price: 45000.0,
    category: 'Food',
  ),
  Product(
    id: 46,
    name: 'Rau Câu',
    description: 'Jelly dessert',
    price: 10000.0,
    category: 'Dessert',
  ),
  Product(
    id: 47,
    name: 'Cháo Lòng',
    description: 'Offal porridge',
    price: 40000.0,
    category: 'Food',
  ),
  Product(
    id: 48,
    name: 'Cacao Sữa Đá',
    description: 'Iced cocoa with condensed milk',
    price: 30000.0,
    category: 'Beverages',
  ),
  Product(
    id: 49,
    name: 'Bánh Pía',
    description: 'Durian pastry',
    price: 25000.0,
    category: 'Dessert',
  ),
  Product(
    id: 50,
    name: 'Gà Nướng',
    description: 'Grilled chicken',
    price: 120000.0,
    category: 'Food',
  ),
  Product(
    id: 51,
    name: 'Trà Atiso',
    description: 'Artichoke tea',
    price: 20000.0,
    category: 'Beverages',
  ),
  Product(
    id: 52,
    name: 'Bánh Trung Thu',
    description: 'Mooncake',
    price: 60000.0,
    category: 'Dessert',
  ),
  Product(
    id: 53,
    name: 'Phở Sốt Vang',
    description: 'Beef stew noodle soup',
    price: 60000.0,
    category: 'Food',
  ),
  Product(
    id: 54,
    name: 'Chè Khoai Môn',
    description: 'Taro sweet soup',
    price: 25000.0,
    category: 'Dessert',
  ),
  Product(
    id: 55,
    name: 'Bánh Gật Gù',
    description: 'Gật Gù cake (rice noodle)',
    price: 30000.0,
    category: 'Food',
  ),
  Product(
    id: 56,
    name: 'Nước Sâm',
    description: 'Herbal drink',
    price: 20000.0,
    category: 'Beverages',
  ),
  Product(
    id: 57,
    name: 'Bánh Đúc Nóng',
    description: 'Hot plain rice flan',
    price: 30000.0,
    category: 'Food',
  ),
  Product(
    id: 58,
    name: 'Chè Trôi Nước',
    description: 'Glutinous rice balls in ginger syrup',
    price: 25000.0,
    category: 'Dessert',
  ),
  Product(
    id: 59,
    name: 'Mì Vịt Tiềm',
    description: 'Duck noodle soup with herbs',
    price: 70000.0,
    category: 'Food',
  ),
];
